=== minrva/mod-wayfinder/src/main/resources/schemas/shelf.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Shelf Schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "permanentLocationId": {
      "type": "string"
    },
    "label": {
      "type": "string"
    },
    "lowerBound": {
      "type": "string"
    },
    "upperBound": {
      "type": "string"
    },
    "mapTitle": {
      "type": "string"
    },
    "mapUri": {
      "type": "string"
    },
    "x": {
      "type": "integer"
    },
    "y": {
      "type": "integer"
    }
  },
  "additionalProperties": false,
  "required": [
    "id",
    "permanentLocationId",
    "label",
    "lowerBound",
    "upperBound",
    "mapTitle",
    "mapUri",
    "x",
    "y"
  ]
}

=== minrva/mod-wayfinder/ramls/examples/shelf1.json
{
  "id": "6f970576-3994-4d25-8d76-346ac67840ae",
  "permanentLocationId": "fcd64ce1-6995-48f0-840e-89ffa2288371",
  "label": "2",
  "lowerBound": "E885 .N5",
  "upperBound": "F541 .M9",
  "mapTitle": "Annex",
  "mapUri": "http://minrva.library.illinois.edu/api/wayfinder/map/2_undergrad_2.png?x=459&y=130",
  "x": 459,
  "y": 130
}

=== minrva/mod-wayfinder/ramls/examples/shelf2.json
{
  "id": "24b9855e-20a8-404b-b62c-6ba5e851f3c3",
  "permanentLocationId": "fcd64ce1-6995-48f0-840e-89ffa2288371",
  "label": "1",
  "lowerBound": "E885 .N5",
  "upperBound": "F541 .M9",
  "mapTitle": "Main",
  "mapUri": "http://minrva.library.illinois.edu/api/wayfinder/map/1_undergrad_2.png?x=459&y=269",
  "x": 459,
  "y": 269
}

=== minrva/mod-wayfinder/src/main/resources/examples/shelf1.json
{
  "id" : "5e91aa9e-a7a8-4f91-9697-d3a321ec8d1c",
  "permanentLocationId" : "fcd64ce1-6995-48f0-840e-89ffa2288371",
  "label" : "2",
  "lowerBound" : "AC8 .B4",
  "upperBound" : "B5234 .F4",
  "mapTitle" : "Main",
  "mapUri" : "https://lh3.googleusercontent.com/QzygfOsk1EZVe3e6EqCxDyZ_TXMnDf_Lm85gs9Vheti7gVXK6sJwaqDQCpuaxQXZDuxXkSH3xOdmrMyxCtXnkfTjWt_sOSNLh2mixrzvl6L-bn384DqXBUAn4Fpuign8gIO4HBcWdw=w2400",
  "x" : 459,
  "y" : 408
}
